"""
Unit Conversion Script for Revenue Extraction Output

This script standardizes extracted revenue values into "万元" and writes a clean Excel output.

Privacy / security notes:
- No local machine paths are hardcoded.
- File paths are provided through command-line arguments.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

import pandas as pd


UNIT_CNY = "元"
UNIT_CNY_WITH_SPACE = " 元"
UNIT_RMB_CNY = "人民币元"
UNIT_THOUSAND = "千元"
UNIT_RMB_THOUSAND = "人民币千元"
UNIT_MILLION = "百万元"
UNIT_RMB_MILLION = "人民币百万元"
UNIT_TEN_THOUSAND = "万元"
UNIT_HUNDRED_MILLION = "亿元"

VAL_NO_DATA = "No Data"
VAL_NO_UNIT = "No Unit"
UNIT_COLUMN = "Unit"

UNIT_CONVERT = {
    UNIT_CNY: (UNIT_TEN_THOUSAND, 1 / 10000),
    UNIT_RMB_CNY: (UNIT_TEN_THOUSAND, 1 / 10000),
    UNIT_THOUSAND: (UNIT_TEN_THOUSAND, 1 / 10),
    UNIT_RMB_THOUSAND: (UNIT_TEN_THOUSAND, 1 / 10),
    UNIT_MILLION: (UNIT_TEN_THOUSAND, 100),
    UNIT_RMB_MILLION: (UNIT_TEN_THOUSAND, 100),
    UNIT_HUNDRED_MILLION: (UNIT_TEN_THOUSAND, 10000),
    UNIT_CNY_WITH_SPACE: (UNIT_TEN_THOUSAND, 1 / 10000),
}


def parse_number(value: object) -> float:
    """Parse a numeric cell that may contain commas."""
    if pd.isna(value):
        raise ValueError("Missing value")
    if isinstance(value, str):
        return float(value.replace(",", "").strip())
    return float(value)


def convert_units(input_file: Path, output_file: Path | None = None, year_cols: Iterable[str] = ("2023", "2022", "2021")) -> Path:
    """Convert revenue values into 万元 and return the written file path."""
    input_file = input_file.expanduser().resolve()
    output_file = output_file.expanduser().resolve() if output_file else input_file

    df = pd.read_excel(input_file)

    if UNIT_COLUMN not in df.columns:
        raise ValueError(f"The '{UNIT_COLUMN}' column was not found in the Excel file.")

    year_cols = list(year_cols)
    missing_cols = [col for col in year_cols if col not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing year columns: {missing_cols}")

    for index, row in df.iterrows():
        unit = str(row[UNIT_COLUMN]).strip() if not pd.isna(row[UNIT_COLUMN]) else ""

        if unit == UNIT_TEN_THOUSAND:
            continue

        if unit not in UNIT_CONVERT:
            df.at[index, UNIT_COLUMN] = VAL_NO_UNIT
            continue

        new_unit, factor = UNIT_CONVERT[unit]
        df.at[index, UNIT_COLUMN] = new_unit

        for col in year_cols:
            try:
                value = parse_number(row[col])
                df.at[index, col] = f"{value * factor:,.0f}"
            except (ValueError, TypeError):
                df.at[index, col] = VAL_NO_DATA

    output_file.parent.mkdir(parents=True, exist_ok=True)
    df.to_excel(output_file, index=False)
    return output_file


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Standardize extracted revenue units into 万元.")
    parser.add_argument("--input-file", required=True, help="Excel file generated by the extraction script.")
    parser.add_argument("--output-file", default=None, help="Optional path for the converted Excel output.")
    parser.add_argument("--year-cols", nargs="+", default=["2023", "2022", "2021"], help="Year columns to convert.")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    written_file = convert_units(
        input_file=Path(args.input_file),
        output_file=Path(args.output_file) if args.output_file else None,
        year_cols=args.year_cols,
    )
    print(f"Unit conversion completed. Output written to: {written_file}")
